backend:
  name: github
  repo: chadalen/personal-website
  branch: Staging

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: blog
    label: Blog
    folder: src/data/blog
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: Body, widget: markdown }
  - name: projects
    label: Projects
    folder: src/data/projects
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: description, label: Description, widget: text }
      - { name: tags, label: Tags, widget: list }
      - { name: previewImage, label: Preview Image, widget: image }
      - { name: freelance, label: Freelance?, widget: boolean }
      - { name: body, label: Body, widget: markdown }
